title: Minimal theme
logo: /assets/img/ChatGPT Image Mar 29, 2025, 04_29_51 PM.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
